/* @flow */
export const REQUEST_COLLECTION = 'REQUEST_COLLECTION';
export const RECEIVE_COLLECTION = 'RECEIVE_COLLECTION';
export const INVALIDATE_COLLECTION = 'INVALIDATE_COLLECTION';

export const REQUEST_ARTIST = 'REQUEST_ARTIST';
export const RECEIVE_ARTIST = 'RECEIVE_ARTIST';
export const REQUEST_ALBUM = 'REQUEST_ALBUM';
export const RECEIVE_ALBUM = 'RECEIVE_ALBUM';

export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST';
export const REMOVE_SONG_FROM_PLAYLIST = 'REMOVE_SONG_FROM_PLAYLIST';
export const CLEAR_PLAYLIST = 'CLEAR_PLAYLIST';
export const MOVE_SONG_TO_POSITION = 'MOVE_SONG_TO_POSITION';

export const SELECT_ARTIST = 'SELECT_ARTIST';
export const UNSELECT_ARTIST = 'UNSELECT_ARTIST';

export const SELECT_ALBUM = 'SELECT_ALBUM';
export const UNSELECT_ALBUM = 'UNSELECT_ALBUM';

export const SET_PLAY_RANDOM_SONG = 'SET_PLAY_RANDOM_SONG';
export const SET_PLAY_RANDOM_ALBUM = 'SET_PLAY_RANDOM_ALBUM';
export const SET_VOLUME = 'SET_VOLUME';

export const REQUEST_SERVER_STATUS = 'REQUEST_SERVER_STATUS';
export const RECEIVE_SERVER_STATUS = 'RECEIVE_SERVER_STATUS';
export const REQUEST_RESCAN_FILES = 'REQUEST_RESCAN_FILES';
export const REQUEST_SERVER_SETTINGS = 'REQUEST_SERVER_SETTINGS';
export const RECEIVE_SERVER_SETTINGS = 'RECEIVE_SERVER_SETTINGS';

export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';

export const REQUEST_SONG_LYRICS = 'REQUEST_SONG_LYRICS';
export const RECEIVE_SONG_LYRICS = 'RECEIVE_SONG_LYRICS';
