export const REQUEST_COLLECTION = 'REQUEST_COLLECTION';
export const RECEIVE_COLLECTION = 'RECEIVE_COLLECTION';
export const INVALIDATE_COLLECTION = 'INVALIDATE_COLLECTION';

export const REQUEST_ARTIST = 'REQUEST_ARTIST';
export const RECEIVE_ARTIST = 'RECEIVE_ARTIST';
export const REQUEST_ALBUM = 'REQUEST_ALBUM';
export const RECEIVE_ALBUM = 'RECEIVE_ALBUM';

export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST';
export const REMOVE_SONG_FROM_PLAYLIST = 'REMOVE_SONG_FROM_PLAYLIST';
export const CLEAR_PLAYLIST = 'CLEAR_PLAYLIST';
export const MOVE_SONG_TO_POSITION = 'MOVE_SONG_TO_POSITION';

export const SELECT_ARTIST = 'SELECT_ARTIST';
export const UNSELECT_ARTIST = 'UNSELECT_ARTIST';

export const SELECT_ALBUM = 'SELECT_ALBUM';
export const UNSELECT_ALBUM = 'UNSELECT_ALBUM';

export const SET_PLAY_RANDOM = 'SET_PLAY_RANDOM';
export const SET_VOLUME = 'SET_VOLUME';

