// flow-typed signature: f4d2ed960b361d8965f4529966510fb0
// flow-typed version: <<STUB>>/bootstrap-webpack_v^0.0.6/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-webpack/bootstrap-scripts.loader' {
  declare module.exports: any;
}

declare module 'bootstrap-webpack/bootstrap-styles.loader' {
  declare module.exports: any;
}

declare module 'bootstrap-webpack/bootstrap.config' {
  declare module.exports: any;
}

declare module 'bootstrap-webpack/index.loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-webpack/bootstrap-scripts.loader.js' {
  declare module.exports: $Exports<'bootstrap-webpack/bootstrap-scripts.loader'>;
}
declare module 'bootstrap-webpack/bootstrap-styles.loader.js' {
  declare module.exports: $Exports<'bootstrap-webpack/bootstrap-styles.loader'>;
}
declare module 'bootstrap-webpack/bootstrap.config.js' {
  declare module.exports: $Exports<'bootstrap-webpack/bootstrap.config'>;
}
declare module 'bootstrap-webpack/index' {
  declare module.exports: $Exports<'bootstrap-webpack'>;
}
declare module 'bootstrap-webpack/index.js' {
  declare module.exports: $Exports<'bootstrap-webpack'>;
}
declare module 'bootstrap-webpack/index.loader.js' {
  declare module.exports: $Exports<'bootstrap-webpack/index.loader'>;
}
