// flow-typed signature: e57ae98c6480078cd8700e34a55eade9
// flow-typed version: <<STUB>>/boron_v^0.2.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boron/Boron' {
  declare module.exports: any;
}

declare module 'boron/DropModal' {
  declare module.exports: any;
}

declare module 'boron/FadeModal' {
  declare module.exports: any;
}

declare module 'boron/FlyModal' {
  declare module.exports: any;
}

declare module 'boron/modalFactory' {
  declare module.exports: any;
}

declare module 'boron/OutlineModal' {
  declare module.exports: any;
}

declare module 'boron/ScaleModal' {
  declare module.exports: any;
}

declare module 'boron/WaveModal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boron/Boron.js' {
  declare module.exports: $Exports<'boron/Boron'>;
}
declare module 'boron/DropModal.js' {
  declare module.exports: $Exports<'boron/DropModal'>;
}
declare module 'boron/FadeModal.js' {
  declare module.exports: $Exports<'boron/FadeModal'>;
}
declare module 'boron/FlyModal.js' {
  declare module.exports: $Exports<'boron/FlyModal'>;
}
declare module 'boron/modalFactory.js' {
  declare module.exports: $Exports<'boron/modalFactory'>;
}
declare module 'boron/OutlineModal.js' {
  declare module.exports: $Exports<'boron/OutlineModal'>;
}
declare module 'boron/ScaleModal.js' {
  declare module.exports: $Exports<'boron/ScaleModal'>;
}
declare module 'boron/WaveModal.js' {
  declare module.exports: $Exports<'boron/WaveModal'>;
}
