// flow-typed signature: 34242e54df6f5782f5a7d90ba19876a5
// flow-typed version: <<STUB>>/m3u_v0.0.2/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'm3u'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'm3u' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'm3u/lib/m3u' {
  declare module.exports: any;
}

declare module 'm3u/lib/writer' {
  declare module.exports: any;
}

declare module 'm3u/lib/writer/extended_writer' {
  declare module.exports: any;
}

declare module 'm3u/lib/writer/http_live_streaming_writer' {
  declare module.exports: any;
}

declare module 'm3u/test/common' {
  declare module.exports: any;
}

declare module 'm3u/test/helper/fixture_helper' {
  declare module.exports: any;
}

declare module 'm3u/test/integration/test-extended-writer' {
  declare module.exports: any;
}

declare module 'm3u/test/integration/test-http-live-streaming-writer' {
  declare module.exports: any;
}

declare module 'm3u/test/integration/test-writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'm3u/index' {
  declare module.exports: $Exports<'m3u'>;
}
declare module 'm3u/index.js' {
  declare module.exports: $Exports<'m3u'>;
}
declare module 'm3u/lib/m3u.js' {
  declare module.exports: $Exports<'m3u/lib/m3u'>;
}
declare module 'm3u/lib/writer.js' {
  declare module.exports: $Exports<'m3u/lib/writer'>;
}
declare module 'm3u/lib/writer/extended_writer.js' {
  declare module.exports: $Exports<'m3u/lib/writer/extended_writer'>;
}
declare module 'm3u/lib/writer/http_live_streaming_writer.js' {
  declare module.exports: $Exports<'m3u/lib/writer/http_live_streaming_writer'>;
}
declare module 'm3u/test/common.js' {
  declare module.exports: $Exports<'m3u/test/common'>;
}
declare module 'm3u/test/helper/fixture_helper.js' {
  declare module.exports: $Exports<'m3u/test/helper/fixture_helper'>;
}
declare module 'm3u/test/integration/test-extended-writer.js' {
  declare module.exports: $Exports<'m3u/test/integration/test-extended-writer'>;
}
declare module 'm3u/test/integration/test-http-live-streaming-writer.js' {
  declare module.exports: $Exports<'m3u/test/integration/test-http-live-streaming-writer'>;
}
declare module 'm3u/test/integration/test-writer.js' {
  declare module.exports: $Exports<'m3u/test/integration/test-writer'>;
}
