// flow-typed signature: 379d790a5169911cd4160486e08e3afc
// flow-typed version: <<STUB>>/react-bs-notifier_v^4.3.2/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bs-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bs-notifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bs-notifier/es/alert-list' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/es/alert-timer' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/es/alert/icon' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/es/alert/index' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/es/alert/styles' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/es/container/index' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/es/container/styles' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/es/index' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/lib/alert-list' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/lib/alert-timer' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/lib/alert/icon' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/lib/alert/index' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/lib/alert/styles' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/lib/container/index' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/lib/container/styles' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/lib/index' {
  declare module.exports: any;
}

declare module 'react-bs-notifier/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bs-notifier/es/alert-list.js' {
  declare module.exports: $Exports<'react-bs-notifier/es/alert-list'>;
}
declare module 'react-bs-notifier/es/alert-timer.js' {
  declare module.exports: $Exports<'react-bs-notifier/es/alert-timer'>;
}
declare module 'react-bs-notifier/es/alert/icon.js' {
  declare module.exports: $Exports<'react-bs-notifier/es/alert/icon'>;
}
declare module 'react-bs-notifier/es/alert/index.js' {
  declare module.exports: $Exports<'react-bs-notifier/es/alert/index'>;
}
declare module 'react-bs-notifier/es/alert/styles.js' {
  declare module.exports: $Exports<'react-bs-notifier/es/alert/styles'>;
}
declare module 'react-bs-notifier/es/container/index.js' {
  declare module.exports: $Exports<'react-bs-notifier/es/container/index'>;
}
declare module 'react-bs-notifier/es/container/styles.js' {
  declare module.exports: $Exports<'react-bs-notifier/es/container/styles'>;
}
declare module 'react-bs-notifier/es/index.js' {
  declare module.exports: $Exports<'react-bs-notifier/es/index'>;
}
declare module 'react-bs-notifier/lib/alert-list.js' {
  declare module.exports: $Exports<'react-bs-notifier/lib/alert-list'>;
}
declare module 'react-bs-notifier/lib/alert-timer.js' {
  declare module.exports: $Exports<'react-bs-notifier/lib/alert-timer'>;
}
declare module 'react-bs-notifier/lib/alert/icon.js' {
  declare module.exports: $Exports<'react-bs-notifier/lib/alert/icon'>;
}
declare module 'react-bs-notifier/lib/alert/index.js' {
  declare module.exports: $Exports<'react-bs-notifier/lib/alert/index'>;
}
declare module 'react-bs-notifier/lib/alert/styles.js' {
  declare module.exports: $Exports<'react-bs-notifier/lib/alert/styles'>;
}
declare module 'react-bs-notifier/lib/container/index.js' {
  declare module.exports: $Exports<'react-bs-notifier/lib/container/index'>;
}
declare module 'react-bs-notifier/lib/container/styles.js' {
  declare module.exports: $Exports<'react-bs-notifier/lib/container/styles'>;
}
declare module 'react-bs-notifier/lib/index.js' {
  declare module.exports: $Exports<'react-bs-notifier/lib/index'>;
}
declare module 'react-bs-notifier/webpack.config.js' {
  declare module.exports: $Exports<'react-bs-notifier/webpack.config'>;
}
