// flow-typed signature: f8bda586cb490e7ca5acbd3cf5c1e46b
// flow-typed version: <<STUB>>/webpack-version-file_v^0.1.3/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-version-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-version-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-version-file/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-version-file/src/index' {
  declare module.exports: any;
}

declare module 'webpack-version-file/test/data' {
  declare module.exports: any;
}

declare module 'webpack-version-file/test/misc' {
  declare module.exports: any;
}

declare module 'webpack-version-file/test/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-version-file/lib/index.js' {
  declare module.exports: $Exports<'webpack-version-file/lib/index'>;
}
declare module 'webpack-version-file/src/index.js' {
  declare module.exports: $Exports<'webpack-version-file/src/index'>;
}
declare module 'webpack-version-file/test/data.js' {
  declare module.exports: $Exports<'webpack-version-file/test/data'>;
}
declare module 'webpack-version-file/test/misc.js' {
  declare module.exports: $Exports<'webpack-version-file/test/misc'>;
}
declare module 'webpack-version-file/test/options.js' {
  declare module.exports: $Exports<'webpack-version-file/test/options'>;
}
