// flow-typed signature: 2bc48efff3020f793a72db1bea03fb9c
// flow-typed version: <<STUB>>/babel-env_v^2.4.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-env' {
  declare module.exports: any;
}
