// flow-typed signature: be126afaa88d874ad8f231590ffb6540
// flow-typed version: <<STUB>>/babel-env_v^2.4.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-env' {
  declare module.exports: any;
}
