// flow-typed signature: 5b9d415935ea8b757e43f5de1fa3bcc5
// flow-typed version: <<STUB>>/babel-env_v^2.4.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-env' {
  declare module.exports: any;
}
