// flow-typed signature: f4a28e31cf90d557e603a9ae85d43356
// flow-typed version: <<STUB>>/connect-history-api-fallback_v^1.3.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-history-api-fallback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-history-api-fallback' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-history-api-fallback/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-history-api-fallback/lib/index.js' {
  declare module.exports: $Exports<'connect-history-api-fallback/lib/index'>;
}
