// flow-typed signature: 87386bfc009f3de8cf79e9685265a7d6
// flow-typed version: <<STUB>>/musicmetadata_v^2.0.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'musicmetadata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'musicmetadata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'musicmetadata/dist/musicmetadata' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/asf' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/browser' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/common' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/flac' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/id3v1' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/id3v2_frames' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/id3v2' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/id4' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/index' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/monkeysaudio' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/ogg' {
  declare module.exports: any;
}

declare module 'musicmetadata/lib/windows1252decoder' {
  declare module.exports: any;
}

// Filename aliases
declare module 'musicmetadata/dist/musicmetadata.js' {
  declare module.exports: $Exports<'musicmetadata/dist/musicmetadata'>;
}
declare module 'musicmetadata/lib/asf.js' {
  declare module.exports: $Exports<'musicmetadata/lib/asf'>;
}
declare module 'musicmetadata/lib/browser.js' {
  declare module.exports: $Exports<'musicmetadata/lib/browser'>;
}
declare module 'musicmetadata/lib/common.js' {
  declare module.exports: $Exports<'musicmetadata/lib/common'>;
}
declare module 'musicmetadata/lib/flac.js' {
  declare module.exports: $Exports<'musicmetadata/lib/flac'>;
}
declare module 'musicmetadata/lib/id3v1.js' {
  declare module.exports: $Exports<'musicmetadata/lib/id3v1'>;
}
declare module 'musicmetadata/lib/id3v2_frames.js' {
  declare module.exports: $Exports<'musicmetadata/lib/id3v2_frames'>;
}
declare module 'musicmetadata/lib/id3v2.js' {
  declare module.exports: $Exports<'musicmetadata/lib/id3v2'>;
}
declare module 'musicmetadata/lib/id4.js' {
  declare module.exports: $Exports<'musicmetadata/lib/id4'>;
}
declare module 'musicmetadata/lib/index.js' {
  declare module.exports: $Exports<'musicmetadata/lib/index'>;
}
declare module 'musicmetadata/lib/monkeysaudio.js' {
  declare module.exports: $Exports<'musicmetadata/lib/monkeysaudio'>;
}
declare module 'musicmetadata/lib/ogg.js' {
  declare module.exports: $Exports<'musicmetadata/lib/ogg'>;
}
declare module 'musicmetadata/lib/windows1252decoder.js' {
  declare module.exports: $Exports<'musicmetadata/lib/windows1252decoder'>;
}
