// flow-typed signature: 62336781370cc036e687709fe19ab69d
// flow-typed version: <<STUB>>/restify-plugins_v^1.6.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'restify-plugins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'restify-plugins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'restify-plugins/lib/index' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/accept' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/afterLogger' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/audit' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/auditFormatter' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/authorization' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/bodyParser' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/bodyReader' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/bunyan' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/conditionalRequest' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/cors' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/date' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/fieldedTextBodyParser' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/formBodyParser' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/fullResponse' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/gzip' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/jsonBodyParser' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/jsonp' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/metrics' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/multipartBodyParser' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/oauth2TokenParser' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/query' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/requestExpiry' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/static' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/plugins/throttle' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/pre/context' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/pre/dedupeSlashes' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/pre/pause' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/pre/prePath' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/pre/reqIdHeaders' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/pre/strictQueryParams' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/pre/userAgent' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/utils/httpDate' {
  declare module.exports: any;
}

declare module 'restify-plugins/lib/utils/shallowCopy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'restify-plugins/lib/index.js' {
  declare module.exports: $Exports<'restify-plugins/lib/index'>;
}
declare module 'restify-plugins/lib/plugins/accept.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/accept'>;
}
declare module 'restify-plugins/lib/plugins/afterLogger.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/afterLogger'>;
}
declare module 'restify-plugins/lib/plugins/audit.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/audit'>;
}
declare module 'restify-plugins/lib/plugins/auditFormatter.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/auditFormatter'>;
}
declare module 'restify-plugins/lib/plugins/authorization.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/authorization'>;
}
declare module 'restify-plugins/lib/plugins/bodyParser.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/bodyParser'>;
}
declare module 'restify-plugins/lib/plugins/bodyReader.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/bodyReader'>;
}
declare module 'restify-plugins/lib/plugins/bunyan.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/bunyan'>;
}
declare module 'restify-plugins/lib/plugins/conditionalRequest.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/conditionalRequest'>;
}
declare module 'restify-plugins/lib/plugins/cors.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/cors'>;
}
declare module 'restify-plugins/lib/plugins/date.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/date'>;
}
declare module 'restify-plugins/lib/plugins/fieldedTextBodyParser.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/fieldedTextBodyParser'>;
}
declare module 'restify-plugins/lib/plugins/formBodyParser.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/formBodyParser'>;
}
declare module 'restify-plugins/lib/plugins/fullResponse.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/fullResponse'>;
}
declare module 'restify-plugins/lib/plugins/gzip.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/gzip'>;
}
declare module 'restify-plugins/lib/plugins/jsonBodyParser.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/jsonBodyParser'>;
}
declare module 'restify-plugins/lib/plugins/jsonp.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/jsonp'>;
}
declare module 'restify-plugins/lib/plugins/metrics.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/metrics'>;
}
declare module 'restify-plugins/lib/plugins/multipartBodyParser.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/multipartBodyParser'>;
}
declare module 'restify-plugins/lib/plugins/oauth2TokenParser.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/oauth2TokenParser'>;
}
declare module 'restify-plugins/lib/plugins/query.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/query'>;
}
declare module 'restify-plugins/lib/plugins/requestExpiry.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/requestExpiry'>;
}
declare module 'restify-plugins/lib/plugins/static.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/static'>;
}
declare module 'restify-plugins/lib/plugins/throttle.js' {
  declare module.exports: $Exports<'restify-plugins/lib/plugins/throttle'>;
}
declare module 'restify-plugins/lib/pre/context.js' {
  declare module.exports: $Exports<'restify-plugins/lib/pre/context'>;
}
declare module 'restify-plugins/lib/pre/dedupeSlashes.js' {
  declare module.exports: $Exports<'restify-plugins/lib/pre/dedupeSlashes'>;
}
declare module 'restify-plugins/lib/pre/pause.js' {
  declare module.exports: $Exports<'restify-plugins/lib/pre/pause'>;
}
declare module 'restify-plugins/lib/pre/prePath.js' {
  declare module.exports: $Exports<'restify-plugins/lib/pre/prePath'>;
}
declare module 'restify-plugins/lib/pre/reqIdHeaders.js' {
  declare module.exports: $Exports<'restify-plugins/lib/pre/reqIdHeaders'>;
}
declare module 'restify-plugins/lib/pre/strictQueryParams.js' {
  declare module.exports: $Exports<'restify-plugins/lib/pre/strictQueryParams'>;
}
declare module 'restify-plugins/lib/pre/userAgent.js' {
  declare module.exports: $Exports<'restify-plugins/lib/pre/userAgent'>;
}
declare module 'restify-plugins/lib/utils/httpDate.js' {
  declare module.exports: $Exports<'restify-plugins/lib/utils/httpDate'>;
}
declare module 'restify-plugins/lib/utils/shallowCopy.js' {
  declare module.exports: $Exports<'restify-plugins/lib/utils/shallowCopy'>;
}
