// flow-typed signature: b2841578819687b315d542a74d1df1ba
// flow-typed version: <<STUB>>/sonos_v^0.15.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sonos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sonos' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sonos/lib/events/listener' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/AlarmClock' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/AudioIn' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/AVTransport' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/ContentDirectory' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/DeviceProperties' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/GroupManagement' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/GroupRenderingControl' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/MusicServices' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/RenderingControl' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/Service' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/SystemProperties' {
  declare module.exports: any;
}

declare module 'sonos/lib/services/ZoneGroupTopology' {
  declare module.exports: any;
}

declare module 'sonos/lib/sonos' {
  declare module.exports: any;
}

declare module 'sonos/test/sonos.onsite.test' {
  declare module.exports: any;
}

declare module 'sonos/test/sonos.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sonos/index' {
  declare module.exports: $Exports<'sonos'>;
}
declare module 'sonos/index.js' {
  declare module.exports: $Exports<'sonos'>;
}
declare module 'sonos/lib/events/listener.js' {
  declare module.exports: $Exports<'sonos/lib/events/listener'>;
}
declare module 'sonos/lib/services/AlarmClock.js' {
  declare module.exports: $Exports<'sonos/lib/services/AlarmClock'>;
}
declare module 'sonos/lib/services/AudioIn.js' {
  declare module.exports: $Exports<'sonos/lib/services/AudioIn'>;
}
declare module 'sonos/lib/services/AVTransport.js' {
  declare module.exports: $Exports<'sonos/lib/services/AVTransport'>;
}
declare module 'sonos/lib/services/ContentDirectory.js' {
  declare module.exports: $Exports<'sonos/lib/services/ContentDirectory'>;
}
declare module 'sonos/lib/services/DeviceProperties.js' {
  declare module.exports: $Exports<'sonos/lib/services/DeviceProperties'>;
}
declare module 'sonos/lib/services/GroupManagement.js' {
  declare module.exports: $Exports<'sonos/lib/services/GroupManagement'>;
}
declare module 'sonos/lib/services/GroupRenderingControl.js' {
  declare module.exports: $Exports<'sonos/lib/services/GroupRenderingControl'>;
}
declare module 'sonos/lib/services/MusicServices.js' {
  declare module.exports: $Exports<'sonos/lib/services/MusicServices'>;
}
declare module 'sonos/lib/services/RenderingControl.js' {
  declare module.exports: $Exports<'sonos/lib/services/RenderingControl'>;
}
declare module 'sonos/lib/services/Service.js' {
  declare module.exports: $Exports<'sonos/lib/services/Service'>;
}
declare module 'sonos/lib/services/SystemProperties.js' {
  declare module.exports: $Exports<'sonos/lib/services/SystemProperties'>;
}
declare module 'sonos/lib/services/ZoneGroupTopology.js' {
  declare module.exports: $Exports<'sonos/lib/services/ZoneGroupTopology'>;
}
declare module 'sonos/lib/sonos.js' {
  declare module.exports: $Exports<'sonos/lib/sonos'>;
}
declare module 'sonos/test/sonos.onsite.test.js' {
  declare module.exports: $Exports<'sonos/test/sonos.onsite.test'>;
}
declare module 'sonos/test/sonos.test.js' {
  declare module.exports: $Exports<'sonos/test/sonos.test'>;
}
